#!/usr/bin/env python3
"""
Dashboard Build Script
Generates the dashboard by copying templates and data to the output directory.
"""

import json
import os
import shutil
import sys
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parent.parent

DASHBOARD_JSON_PATH = str(_PROJECT_ROOT / 'data' / 'dashboard.json')
CHART_HISTORY_JSON_PATH = str(_PROJECT_ROOT / 'data' / 'chart_history.json')
BREADTH_JSON_PATH = str(_PROJECT_ROOT / 'data' / 'breadth.json')
DASHBOARD_OUTPUT_DIR = str(_PROJECT_ROOT / 'dashboard')
ASSETS_OUTPUT_DIR = str(_PROJECT_ROOT / 'dashboard' / 'assets')


def main():
    """Main execution function."""
    print("=" * 60)
    print("Dashboard Build Script")
    print("=" * 60)
    print()
    
    # Check if dashboard.json exists
    if not os.path.exists(DASHBOARD_JSON_PATH):
        print(f"ERROR: {DASHBOARD_JSON_PATH} not found")
        print("Please run calculate_metrics.py first to generate dashboard.json")
        sys.exit(1)
    
    # Validate dashboard.json structure before copying
    print("Validating dashboard.json structure...")
    try:
        with open(DASHBOARD_JSON_PATH, 'r', encoding='utf-8') as f:
            dashboard_data = json.load(f)
        
        if 'metadata' not in dashboard_data:
            print("ERROR: dashboard.json missing 'metadata' section")
            sys.exit(1)
        
        if 'assets' not in dashboard_data:
            print("ERROR: dashboard.json missing 'assets' section")
            sys.exit(1)
        
        print(f"✓ Valid dashboard.json with {len(dashboard_data['assets'])} assets")
        print(f"✓ Last updated: {dashboard_data['metadata'].get('last_updated', 'Unknown')}")
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON in dashboard.json: {e}")
        sys.exit(1)
    print()
    
    # Create output directories
    print("Creating output directories...")
    os.makedirs(ASSETS_OUTPUT_DIR, exist_ok=True)
    print(f"✓ Created {ASSETS_OUTPUT_DIR}")
    print()
    
    # Copy dashboard.json to assets directory
    print("Copying dashboard data...")
    shutil.copy2(DASHBOARD_JSON_PATH, os.path.join(ASSETS_OUTPUT_DIR, 'data.json'))
    print(f"✓ Copied {DASHBOARD_JSON_PATH} to {ASSETS_OUTPUT_DIR}/data.json")
    print()

    # Copy chart_history.json to assets directory (optional — generated by calculate_metrics.py)
    if os.path.exists(CHART_HISTORY_JSON_PATH):
        shutil.copy2(CHART_HISTORY_JSON_PATH, os.path.join(ASSETS_OUTPUT_DIR, 'chart_history.json'))
        print(f"✓ Copied chart_history.json to {ASSETS_OUTPUT_DIR}/chart_history.json")
    else:
        print("  (chart_history.json not found — skipping; charts will show placeholder)")

    if os.path.exists(BREADTH_JSON_PATH):
        shutil.copy2(BREADTH_JSON_PATH, os.path.join(ASSETS_OUTPUT_DIR, 'breadth.json'))
        print(f"✓ Copied breadth.json to {ASSETS_OUTPUT_DIR}/breadth.json")
    else:
        print("  (breadth.json not found — skipping; breadth chart will be hidden)")
    print()
    
    # Verify required static files are in place
    print("Verifying static files...")
    required_files = [
        os.path.join(DASHBOARD_OUTPUT_DIR, 'index.html'),
        os.path.join(DASHBOARD_OUTPUT_DIR, 'css', 'styles.css'),
        os.path.join(DASHBOARD_OUTPUT_DIR, 'js', 'dashboard.js'),
    ]
    for path in required_files:
        if os.path.exists(path):
            print(f"✓ {path}")
        else:
            print(f"ERROR: Required file not found: {path}")
            sys.exit(1)
    print()

    # Print summary
    index_path = os.path.join(DASHBOARD_OUTPUT_DIR, 'index.html')
    print("=" * 60)
    print("Dashboard build completed successfully")
    print("=" * 60)
    print(f"Output directory: {DASHBOARD_OUTPUT_DIR}")
    print(f"  - {ASSETS_OUTPUT_DIR}/data.json")
    if os.path.exists(os.path.join(ASSETS_OUTPUT_DIR, 'chart_history.json')):
        print(f"  - {ASSETS_OUTPUT_DIR}/chart_history.json")
    print()
    print("To view the dashboard locally, open:")
    print(f"  file://{os.path.abspath(index_path)}")
    print()


if __name__ == "__main__":
    main()
